# Generated by Django 3.2.23 on 2023-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gender', models.CharField(default='Both', max_length=50)),
                ('image', models.ImageField(default='clothes.png', upload_to='')),
                ('description', models.TextField(default='No description available', max_length=300)),
            ],
        ),
    ]
